<?php

namespace AppBundle\Repository;

/**
 * ShortLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
