<?php

namespace AppBundle\Repository;

/**
 * ShortLinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortLinksRepository extends \Doctrine\ORM\EntityRepository
{
}
